src/expences/urls.py
from django.urls import path
from . import views

app_name = 'expences'

urlpatterns = [
    path("create", views.CreateExpences.as_view(), name="create"),
    path("update/<int:pk>", views.UpdateExpences.as_view(), name="update"),
    path("detail/<int:pk>", views.DetailExpences.as_view(), name="detail"),
    path("delete/<int:pk>", views.DeleteExpences.as_view(), name="delete"),
    path("list/", views.ListExpences.as_view(), name="list"),
    path("", views.expences_view, name="main"),
    path("recalculation/", views.recalculation, name="recalculation"),
    path("create-base-info/", views.AddBaseInfoView.as_view(), name="create-base-info"),

    path("create-s", views.CreateIncome.as_view(), name="create-s"),
    path("update-s/<int:pk>", views.UpdateIncome.as_view(), name="update-s"),
    path("detail-s/<int:pk>", views.DetailIncome.as_view(), name="detail-s"),
    path("delete-s/<int:pk>", views.DeleteIncome.as_view(), name="delete-s"),
    path("list-s/", views.ListIncome.as_view(), name="list-s"),

    path("create-per-day", views.CreatePerDay.as_view(), name="create-per-day"),
    path("update-per-day/<int:pk>", views.UpdatePerDay.as_view(), name="update-per-day"),

    path("reserv/<int:pk>", views.UpdateReserv.as_view(), name="reserv"),

    path("create-a/", views.CreateAdditional.as_view(), name="create-a"),
    path("update-a/<int:pk>", views.UpdateAdditional.as_view(), name="update-a"),
    path("delete-a/<int:pk>", views.DeleteAdditional.as_view(), name="delete-a"),
    path("list-a/", views.ListAdditional.as_view(), name="list-a"),

    path("daily-consumption/", views.daily_consumption, name="daily-consumption"),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='homepage/login_dj.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include('homepage.urls', namespace='homepage')),
    path("expences/", include('expences.urls'), name="expences"),
    path("notes/", include('notes.urls'), name="notes"),
    path("user/", include('user_register.urls'), name="user"),
    path("sport/", include('sport.urls'), name="sport")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/expences/models.py
from django.db import models
from django.contrib.auth import get_user_model

S_user = get_user_model()


#  данные пользователя(расход на день, дата получения ЗП, способ расчета, реальны баланс карты)
class PerDay(models.Model):

    X = 'Расчет за полный месяц'
    Y = 'Расчет по факту зачисления'

    CHOISE_GROUP = {
        (X, 'Расчет за полный месяц'),
        (Y, 'Расчет по мере зачисления на карту'),
    }
    user = models.OneToOneField(
        S_user,
        verbose_name="Пользователь",
        related_name='user_per_day',
        on_delete=models.CASCADE
    )
    # сумма расхода на день
    value = models.DecimalField(
        verbose_name='Расход на день',
        max_digits=10,
        decimal_places=2
    )
    # поле, которое будет заполняться для рассчета ЗП(день получения зп)
    day = models.DateField(
        verbose_name='День зарплаты'

    )
    # Указания способа расчета. расчет за полный месяц(аванс+ЗП) или по мере поступления денег на карту
    salary_method = models.CharField(
        verbose_name='Способ расчета',
        max_length=50,
        choices=CHOISE_GROUP,
        default=X)

    # реальный баланс карты
    balance = models.DecimalField(
        verbose_name='Реальный баланс карты',
        max_digits=100,
        decimal_places=2,
        default=0
    )



# расходы
class Expediture(models.Model):
    user = models.ForeignKey(
        S_user,
        verbose_name="Пользователь",
        related_name='user_expences',
        on_delete=models.CASCADE)
    name = models.CharField(
        verbose_name='Наименование',
        max_length=50)
    value = models.DecimalField(
        verbose_name='Значение',
        max_digits=10,
        decimal_places=2
    )
    date = models.DateField(
        verbose_name='дата изменения',
        auto_now=True
    )
    status = models.BooleanField(
        verbose_name='Оплачено'
    )
    description = models.TextField(
        verbose_name='Описание',
        max_length=500,
        blank=True,
        null=True
    )


# аванс/зарплата
class Salary(models.Model):
    X = 'аванс'
    Y = 'зарплата'

    CHOISE_GROUP = {
        (X, 'аванс'),
        (Y, 'зарплата'),
    }

    user = models.ForeignKey(
        S_user,
        verbose_name="Пользователь",
        related_name='user_salary',
        on_delete=models.CASCADE)
    name = models.CharField(
        verbose_name='Наименование',
        max_length=50,
        choices=CHOISE_GROUP,
        default=Y)
    value = models.DecimalField(
        verbose_name='Значение',
        max_digits=10,
        decimal_places=2
    )
    date = models.DateField(
        verbose_name='дата изменения',
        auto_now_add=True
    )
    status = models.BooleanField(
        verbose_name='статус',
        default=True
    )


# дополнительные доходы
class AdditionalIncome(models.Model):
    user = models.ForeignKey(
        S_user,
        verbose_name="Пользователь",
        related_name='user_additional_income',
        on_delete=models.CASCADE)
    name = models.CharField(
        verbose_name='Наименование',
        max_length=50,
    )
    value = models.DecimalField(
        verbose_name='Значение',
        max_digits=10,
        decimal_places=2
    )
    date = models.DateField(
        verbose_name='дата изменения',
        auto_now_add=True
    )
    status = models.BooleanField(
        verbose_name='Использован',
        default=True
    )


# резерв
class Reserv(models.Model):
    user = models.OneToOneField(
        S_user,
        verbose_name="Пользователь",
        related_name='user_reserv',
        on_delete=models.CASCADE
    )

    value = models.DecimalField(
        verbose_name='Значение',
        max_digits=100,
        decimal_places=2,
        default=0
    )

    date = models.DateField(
        verbose_name='Дата изменения',
        auto_now_add=True
    )


class DailyConsumption(models.Model):
    user = models.OneToOneField(
        S_user,
        verbose_name="Пользователь",
        related_name='user_daily_cons',
        on_delete=models.CASCADE)

    per_month = models.DecimalField(
        verbose_name='Месячный остаток',
        max_digits=100,
        decimal_places=2,
        default=0
    )

    buffer_money = models.DecimalField(
        verbose_name='Дневной остаток',
        max_digits=100,
        decimal_places=2,
        default=0
    )

src/expences/forms.py
from django import forms
from . import models


class ExpencesForm(forms.ModelForm):
    class Meta:
        model = models.Expediture
        fields = ('name', 'value', 'status', 'description')


class SalaryForm(forms.ModelForm):
    class Meta:
        model = models.Salary
        fields = ('name', 'value', 'status')


class PerDayForm(forms.ModelForm):
    class Meta:
        model = models.PerDay
        fields = ('value', 'day', 'salary_method', 'balance')


class ReservForm(forms.ModelForm):
    class Meta:
        model = models.Reserv
        fields = ('value',)


class AdditionalIncomeForm(forms.ModelForm):
    class Meta:
        model = models.AdditionalIncome
        fields = ('name', 'value', 'status')


class DailyConsumptionForm(forms.ModelForm):
    class Meta:
        model = models.DailyConsumption
        fields = ('buffer_money',)

src/expences/views.py
from django.shortcuts import render, redirect
from . import models, forms
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import datetime

def day_to(request):
    now_date = datetime.now()
    # now_date = datetime(2021.10.15) => for test
    user_date = request.user.user_per_day.day.day
    some_date2 = datetime(now_date.year, now_date.month, user_date)
    if now_date.month == 12:
        some_date = datetime(now_date.year + 1, 1, user_date)
    else:
        some_date = datetime(now_date.year, now_date.month + 1, user_date)
    
    if now_date.day < some_date.day:
        day_to_salary1 = some_date2 - now_date
    else:
        day_to_salary1 = some_date - now_date
    day_to_salary1 = day_to_salary1.days
    return day_to_salary1

class AddBaseInfoView(LoginRequiredMixin, generic.CreateView):
    model = models.PerDay
    form_class = forms.PerDayForm
    success_url = reverse_lazy('expences:main')
    login_url = reverse_lazy('login')
    template_name = 'expences/add_base_info.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)



@login_required(login_url='login')
def daily_consumption(request):
    try:
        context = {}
        
        day_to_salary1 = day_to(request=request)

        buffer_money = request.user.user_daily_cons.per_month - (request.user.user_per_day.value * day_to_salary1) 
        daily_consumption = request.user.user_daily_cons
        daily_consumption.buffer_money += buffer_money
        daily_consumption.per_month = request.user.user_per_day.value * day_to_salary1
        daily_consumption.save()
        
        reserv, created = models.Reserv.objects.get_or_create(
            user=request.user,
            defaults={'value': 0}
        )
        context['reserv'] = reserv.value
        # context['reserv'] = request.user.user_reserv.value
        context['total_money'] = request.user.user_per_day.balance
        context['per_month'] = request.user.user_daily_cons.per_month
        context['buffer_money'] = request.user.user_daily_cons.buffer_money
        context['days'] = request.user.user_daily_cons.per_month /  request.user.user_per_day.value

        if request.method == "POST":
            spend_money = int(request.POST.get('spend_money'))
            context['spend_money'] = spend_money
            reserv = request.user.user_reserv
            if spend_money > daily_consumption.buffer_money:
                spend_money -= daily_consumption.buffer_money
                reserv.value -= spend_money
                daily_consumption.buffer_money = 0
                daily_consumption.save()
                reserv.save()


                context['alarm'] = 'Вы привысили лимит! Разница будет списана с "резерва".'
                context['reserv_value'] = reserv.value
                context['sum_that_gt'] = abs(daily_consumption.buffer_money - spend_money)

            else:
                daily_consumption.buffer_money -= spend_money
                daily_consumption.save()
                context['spend_money_lt_buffer'] = daily_consumption.buffer_money 

        return render(
                request=request,
                template_name="expences/daily_consumption.html",
                context=context
            )
    except User.user_per_day.RelatedObjectDoesNotExist:
        return redirect('expences:create-base-info')




@login_required(login_url='login')
def expences_view(request):
    try:
        context = {}
        #расчет даты
        day_to_salary1 = day_to(request=request)
        # дни до зарплаты
        context["days_to_salary"] = day_to_salary1
        # сумма на карте до конца месяца на ежедневные расходы

        daily, created = models.DailyConsumption.objects.get_or_create(
            user=request.user,
            defaults={'per_month': day_to_salary1 * request.user.user_per_day.value,
                    'buffer_money': 0            
            }
        )
        context["money_to_salary"] = request.user.user_daily_cons.per_month

        # сумма резерва на карте
        reserv, created = models.Reserv.objects.get_or_create(
            user=request.user,
            defaults={'value': 0}
        )
        if created:
            context[
                'created'] = 'Для расчета необходимо указать ЗП за текущий месяц,обязательные расходы, а потом сделать перерасчет(пересчитать резерв). Данные пункты будут обозначанны "!" '
            context['attention'] = '!'
        context["reserv"] = reserv.value
        # не оплаченные услуги
        not_paid = models.Expediture.objects.filter(
            Q(user=request.user) & Q(status=False))
        sum_of_not_paid = 0
        for val in not_paid:
            sum_of_not_paid += val.value
        context["not_paid"] = sum_of_not_paid

        # сумма дополнительных доходов, которые еще не использованны и все еще на карте
        not_used_additional = models.AdditionalIncome.objects.filter(
            Q(user=request.user) & Q(status=False))
        sum_of_not_used_additional = 0
        for not_used in not_used_additional:
            sum_of_not_used_additional += not_used.value
        context['not_used_additional'] = sum_of_not_used_additional

        # ожидаемый остаток на карте(исходя из данных)
        last_transfer = models.Salary.objects.filter(user = request.user).order_by('-id')[:1]

        ost = request.user.user_daily_cons.per_month + request.user.user_daily_cons.buffer_money + \
            request.user.user_reserv.value + sum_of_not_paid + sum_of_not_used_additional

        if last_transfer:
            if last_transfer[0].name == 'аванс':
                ost += last_transfer[0].value
        context["ost"] = ost

        # буферная сумма и реальный(указанный пользователем баланс карты)
        if request.user.user_per_day.balance:
            context['real_balance'] = request.user.user_per_day.balance
        else:
            context['real_balance'] = 0

        if request.user.user_daily_cons.buffer_money:
            context['buffer_money'] = request.user.user_daily_cons.buffer_money
        else:
            context['buffer_money'] = 0
        

        # временно фильтровать по статусу. далее автоматически
        salary_for_mounth = models.Salary.objects.filter(
            Q(user=request.user) & Q(status=True))
        sum_of_salary = 0
        for salary in salary_for_mounth:
            sum_of_salary += salary.value
        context["salary_for_mounth"] = sum_of_salary

    

        # форма для уточнения резерва исходя из реального(данные которые введут) остатка на карте
        if request.method == 'POST':
            balance = request.POST.get('balance')
            difference = int(balance) - int(ost)
            context['difference'] = difference
            real_user_balance = request.user.user_per_day
            real_user_balance.balance = balance
            real_user_balance.save()
            resrv = request.user.user_reserv.value + difference
            context['real_reserv'] = resrv
            user_res = request.user.user_reserv
            user_res.value = resrv
            user_res.save()

        return render(
            request=request,
            template_name="expences/main.html",
            context=context
        )
    except User.user_per_day.RelatedObjectDoesNotExist:
        return redirect('expences:create-base-info')


@login_required(login_url='login')
def recalculation(request):
    context = {}

    day_to_salary1 = day_to(request=request)

    if request.method == "POST":

        salary_for_mounth = models.Salary.objects.filter(
            Q(user=request.user) & Q(status=True))
        sum_of_salary = 0
        for salary in salary_for_mounth:
            sum_of_salary += salary.value

        all_expediture = models.Expediture.objects.filter(
            user=request.user)
        for expediture in all_expediture:
            expediture.status = False
            expediture.save()

        #  сумма неоплаченных ежемесячных платежей
        not_paid = models.Expediture.objects.filter(
            Q(user=request.user) & Q(status=False))
        sum_of_not_paid = 0
        for val in not_paid:
            sum_of_not_paid += val.value
        context["not_paid"] = sum_of_not_paid
        
        if day_to_salary1 == 0:
            user_day_to_salary1 = 31
        else:
            user_day_to_salary1 = day_to_salary1 
        
        daily_consumption = request.user.user_daily_cons
        daily_consumption.per_month = request.user.user_per_day.value * day_to_salary1
        daily_consumption.save()

        request.user.user_reserv.value = sum_of_salary - sum_of_not_paid - (
            request.user.user_per_day.value * user_day_to_salary1)
        request.user.user_reserv.value_of_days_exp = request.user.user_per_day.value * user_day_to_salary1
        request.user.user_reserv.save()

    return render(
        request=request,
        context=context,
        template_name='expences/recalculation.html'

    )


# расходы

class CreateExpences(LoginRequiredMixin, generic.CreateView):
    model = models.Expediture
    form_class = forms.ExpencesForm
    template_name = "expences/edit_expences.html"
    success_url = reverse_lazy('expences:list')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Создать'
        return context

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)


class UpdateExpences(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.Expediture

src/expences/templates/expences/add_base_info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Ввод доплнительных данных для расчета {% endblock title %}

{% block body %}
<h1>Укажите необходимые данные </h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form |crispy}}
<input type="submit" class="btn btn-success" value="Ok">
</form>
{% endblock body %}

src/expences/templates/expences/daily_consumption.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Дневной расход
{% endblock title %}


{% block body %}
<div class="cons-link-buttons">
    <p><a href="{% url 'expences:daily-consumption' %}"><button type="button" class="daily_cons_main_button">ДНЕВНОЙ ОСТАТОК</button></a></p>
    <p><a href="{% url 'expences:main' %}"><button type="button" class="daily_cons_main_button">БЮЖДЕТ</button></a></p>
</div>

<div class='daily_cons_balance' >
        <a class='link_to_exp-main' href="{% url 'expences:main'  %}#input-real-balance"><p>На счету: {{ total_money }}руб.</a></p>
        <a class='link_to_exp-main' href="{% url 'expences:reserv' pk=user.user_reserv.pk %}"><p>Резерв: {{reserv}}руб.</a> &nbsp &nbsp &nbsp<a class='link_to_exp-main' href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}">{{ days }}(кол-во дней)</p></a>
        <p>Буфферные деньги: {{ buffer_money }} руб</p> 
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>Потраченно денег:  <input id="text-field__input" type="number" name="spend_money" value="0" min="0">
            <button type="submit" class="my_button">ok</button></p>
        </form>
 </div>

<div class="spend_money">
    {% if spend_money %}

    
    <p>Потраченно: {{ spend_money }} руб </p>

    {% if buffer_money >= spend_money %}

    <p>Остаток: {{ spend_money_lt_buffer }}руб </p>

    {% else %} 

    <span class="alarm_message_for_daily_main"><p>{{alarm}}</p></span>
    <span class="alarm_message_for_daily"><p>Сумма списанная с резерва: {{ sum_that_gt }}</p>
    <p>Резерв:{{ reserv_value }}</p></span>
    {% endif %}

    {% endif %}
</div>

{% endblock body %}

src/expences/templates/expences/detali_expences.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<ul>
<li>Название: <b>{{object.name}}</b></li>
<li>Сумма: <b>{{object.value}}</b>BYN</li>
<li>Дата обновления: <b>{{object.date}}</b>BYN</li>
<br><br>
<ul>
{% endblock body %}

src/expences/templates/expences/list_expences-a.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<h1>Дополнительные доходы</h2>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        <td>{{obj.name}}</td>
        <td>{{obj.value}}</td>
        <td>{{obj.user}}</td>
        <td>{{obj.date}}</td>
        <td><a href= "{% url 'expences:update-a' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'expences:delete-a' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>
<h3>Общая сумма: <b>{{total}}</b></h3>
<li><a href="{% url 'expences:create-a' %}">Добавить зачисление на карту( Дополнительный доход)</a></li>

{% endblock body %}

src/expences/templates/expences/list_expences-s.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<h1>Доходы</h2>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        <td>{{obj.name}}</td>
        <td>{{obj.value}}</td>
        <td>{{obj.user}}</td>
        <td>{{obj.date}}</td>
        <td>{{obj.status}}</td>
        <td><a href= "{% url 'expences:detail-s' pk=obj.pk %}" class="btn btn-secondary"><i class="bi bi-info-circle"></i></a></td>
        <td><a href= "{% url 'expences:update-s' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'expences:delete-s' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>
<h3>Общая сумма: <b>{{total}}</b></h3>
<li><a href="{% url 'expences:create-s' %}">Добавить зачисление на карту</a></li>
{% endblock body %}

src/expences/templates/expences/list_expences.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<h1>Расходы</h1>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        {% if obj.status == False %}
        <td>{{obj.name}} </td>
        <td>{{obj.value}}</td>
        <td>{{obj.user}}</td>
        <td>{{obj.date}}</td>
        <td> 
            {% if obj.status == False %}
            Не оплачено
            {% else %}
            Оплачено
            {% endif %}
        </td>
        {% else %}
        <td><s>{{obj.name}} </s></td>
         <td><s>{{obj.value}}</s></td>
        {% comment %} <td><s>{{obj.user}}</s></td> {% endcomment %}
        <td><s>{{obj.date}}</s></td>
        <td>
            {% if obj.status == False %}
            Не оплачено
            {% else %}
            Оплачено
            {% endif %}
        </td>
        {% endif %}
        <td><a href= "{% url 'expences:detail' pk=obj.pk %}" class="btn btn-secondary"><i class="bi bi-info-circle"></i></a></td>
        <td><a href= "{% url 'expences:update' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'expences:delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>
<h4>На дневные расходы до конца месяца: <b>{{ daily_consumption }}</b></h4>
<h4>Общая сумма обязательных расходов: <b>{{total_to_pay}}</b></h4>
<h4>Сумма неоплаченных обязательных расходов: <b> {% if total_exp == 0 %} Все оплачено {% else %}{{ total_exp }}{% endif %}</b></h4>
<h4>Осталось оплатить услуги на сумму: <b>{{total}}</b></h4>
<li><a href="{% url 'expences:create' %}">Добавить статью расходов</a></li>
{% endblock body %}

src/expences/templates/expences/main.html
{% extends 'base.html' %}





{% block body %}

<a href="javascript:history.back()"><button type="button" class="btn btn-dark"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<br><br>
<div class="created">
{% if created %}
<p>{{ created }}</p>
{% endif %}
</div>

<div class="cons-link-buttons">
<p><a href="{% url 'expences:main' %}"><button type="button" class="daily_cons_main_button"><span class="created-span">{{attention}}</span> БЮДЖЕТ</button></a></p>

<p><a href="{% url 'expences:daily-consumption' %}"><button type="button" class="daily_cons_main_button">ДНЕВНОЙ ОСТАТОК</button></a></p>
<details>
    <summary class="daily_cons_main_button">Данные(детальнее)</summary>
<p><a href="{% url 'expences:list' %}"><button type="button" class="daily_cons_main_button"><span class="created-span">{{attention}}</span> Расходы</button></a></p>
<p><a href="{% url 'expences:list-s' %}"><button type="button" class="daily_cons_main_button"><span class="created-span">{{attention}}</span> Основной доход</button></a></p>
<p><a href="{% url 'expences:list-a' %}"><button type="button" class="daily_cons_main_button">Дополнительные доходы</button></a></p>
<p><a href="{% url 'expences:reserv' pk=user.user_reserv.pk %}"><button type="button" class="daily_cons_main_button">Изменить резерв</button></a></p>
<p><a href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}" class="text"><button type="button" class="daily_cons_main_button">Основные данные</button></a></p>
<p><a href="{% url 'expences:recalculation' %}"><button type="button" class="daily_cons_main_button"><span class="created-span">{{attention}}</span> Пересчитать резерв</button></a></p>
</details>
</div>


<div class="exp-main-balance-info">

    <a href="{% url 'expences:list-s' %} " class="exp-links-text">
    <p>Основной доход за месяц:{{ salary_for_mounth }} руб </p>
    <hr/>
    </a>


    <a href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}" class="exp-links-text">
    <p>Дней до зарплаты:{{ days_to_salary }}</p>
    <hr/>
    </a>

    <a href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}" class="exp-links-text">
    <p>На ежедневыне расходы до конца месяца:{{ money_to_salary }}руб(расчетный остаток)</p>
    <hr/>
    </a>

    {% if not_paid != 0 %}
    <a href="{% url 'expences:list' %}" class="exp-links-text">
    <p>Сумма не оплаченых платежей:{{not_paid}} руб</p>
    <hr/>
    </a>
    {% endif %}

    <a href="{% url 'expences:reserv' pk=user.user_reserv.pk %}" class="exp-links-text">
    <p>Резерв: {{ reserv }} руб</p>
    <hr/>
    </a>

    {% if buffer_money != 0 %}
    <a href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}" class="exp-links-text">
    <p>"Буфферные" деньги:{{ buffer_money }} руб </p>
    <hr/>
    </a>
    {% endif %}

    <a href="{% url 'expences:main' %}" class="exp-links-text">
    <p>Прогнозируемый остаток на карте:{{ ost }} руб</p>
    <hr/>
    </a>

    {% if real_balance != 0 %}
    <a href="{% url 'expences:update-per-day' pk=user.user_per_day.pk %}" class="exp-links-text">
    <p>Действительный баланс карты: {{ real_balance }} руб</p>
    <hr/>
    </a>
    {% endif %}

 
    {% if not_used_additional != 0 %}
    <a href="{% url 'expences:list-a' %}" class="exp-links-text">
    <p>Дополнительный неиспользованный доход: {{ not_used_additional }}руб</p>
    <hr/>
    </a>
    {% endif %}
</div>

<div class="exp-input-real-balance" >
<form id='balance'  action="{% url 'expences:main' %}" method="post">
    {% csrf_token %}
    <p>Реальный баланс карты:  <input id="input-real-balance" type="number" name="balance" value="{{ real_balance }}" min="0">
    <button type="submit" class="my_button">ok</button></p>
</form>
</div>

<div class="spend_money">
{% if difference %}
<p>Разница с реальным счетом: {{difference}}</p>
<p>Резерв: {{real_reserv}}</p>
{% endif %}
</div>
{% endblock body %}