src/expences/urls.py
from django.urls import path
from . import views

app_name = 'expences'

urlpatterns = [
    path("create", views.CreateExpences.as_view(), name="create"),
    path("update/<int:pk>", views.UpdateExpences.as_view(), name="update"),
    path("detail/<int:pk>", views.DetailExpences.as_view(), name="detail"),
    path("delete/<int:pk>", views.DeleteExpences.as_view(), name="delete"),
    path("list/", views.ListExpences.as_view(), name="list"),
    path("", views.expences_view, name="main"),
    path("recalculation/", views.recalculation, name="recalculation"),
    path("create-base-info/", views.AddBaseInfoView.as_view(), name="create-base-info"),

    path("create-s", views.CreateIncome.as_view(), name="create-s"),
    path("update-s/<int:pk>", views.UpdateIncome.as_view(), name="update-s"),
    path("detail-s/<int:pk>", views.DetailIncome.as_view(), name="detail-s"),
    path("delete-s/<int:pk>", views.DeleteIncome.as_view(), name="delete-s"),
    path("list-s/", views.ListIncome.as_view(), name="list-s"),

    path("create-per-day", views.CreatePerDay.as_view(), name="create-per-day"),
    path("update-per-day/<int:pk>", views.UpdatePerDay.as_view(), name="update-per-day"),

    path("reserv/<int:pk>", views.UpdateReserv.as_view(), name="reserv"),

    path("create-a/", views.CreateAdditional.as_view(), name="create-a"),
    path("update-a/<int:pk>", views.UpdateAdditional.as_view(), name="update-a"),
    path("delete-a/<int:pk>", views.DeleteAdditional.as_view(), name="delete-a"),
    path("list-a/", views.ListAdditional.as_view(), name="list-a"),

    path("daily-consumption/", views.daily_consumption, name="daily-consumption"),
]

src/homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path("", views.HomepageView.as_view(), name='home'),
]

src/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path("", views.NotesView.as_view(), name='main'),
    path("create/", views.CreateNote.as_view(), name='create'),
    path("update/<int:pk>", views.UpdateNote.as_view(), name='update'),
    path("list", views.ListNote.as_view(), name='list'),
    path("delete/<int:pk>", views.DeleteNote.as_view(), name='delete'),
    path("detail/<int:pk>", views.DetailNote.as_view(), name='detail'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='homepage/login_dj.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include('homepage.urls', namespace='homepage')),
    path("expences/", include('expences.urls'), name="expences"),
    path("notes/", include('notes.urls'), name="notes"),
    path("user/", include('user_register.urls'), name="user"),
    path("sport/", include('sport.urls'), name="sport")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sport/urls.py
from django.urls import path
from . import views

app_name = "sport"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="main"),

    path("subscription/", views.SubscriptionView.as_view(), name="subscription"),
    path("create-subscription", views.SubscriptionCreateView.as_view(), name="create-subscription"),
    path("list-subscription/", views.SubscriptionListView.as_view(), name="list-subscription"),
    path("update-subscription/<int:pk>", views.SubscriptionUpdateView.as_view(), name="update-subscription"),
    path("detail-subscription/<int:pk>", views.SubscriptionDetailView.as_view(), name="detail-subscription"),
    path("delete-subscription/<int:pk>", views.SubscriptionDeleteView.as_view(), name="delete-subscription"),


    path("create-subscription-visit", views.SubscriptionVisitCreateView.as_view(), name="create-subscription-visit"),
    path("list-subscription-visit/", views.SubscriptionVisitListView.as_view(), name="list-subscription-visit"),
    path("update-subscription-visit/<int:pk>", views.SubscriptionVisitUpdateView.as_view(), name="update-subscription-visit"),
    path("delete-subscription-visit/<int:pk>", views.SubscriptionVisitDeleteView.as_view(), name="delete-subscription-visit"),

]

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru" class="h-100">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> {% block title %} Органайзер {% endblock title %} </title>


<link href={% static "bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
<link href={% static "icons/bootstrap-icons.css" %} rel="stylesheet">
<link href={% static "bootstrap/css/custom.css" %} rel="stylesheet">



<meta name="theme-color" content="#712cf9">
  </head>
  <body class="d-flex flex-column bg-dark h-100">
    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'homepage:home' %}">Главная</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'expences:daily-consumption' %}">Бюджет</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'notes:main' %}">Заметки</a>
          </li> {% endcomment %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'sport:main'  %}">Спорт</a>
          </li>


          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Войти</a>
          </li>
          {% endif %} 
          
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="">Привет,{{user}}</a>
          </li>
          {% endif %}
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="/admin/">Django admin</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link disabled" >{% now "l d.m.Y" %}</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

<main class="p-3 mb-2 bg-dark text-white">
  <div class="container">
  {% block body %}
   
  {% endblock body %}
  </div>
</main>

<footer class="footer mt-auto py-3 bg-dark text-white">
  <div class="container">
    <span class="text-muted"> 
    {% block footer %}
    <p class="link_to_exp-main">Developed by Maksim Ivanov. <a href="mailto:makisim.ivanov.blr@gmail.com" class="link_to_exp-main">Сontact me (email)</a></p>
    {% endblock footer %} 
    </span>
  </div>
</footer>
    <script src={% static "bootstrap/js/bootstrap.bundle.min.js" %} ></script>
    <script src={% static "bootstrap/js/bootstrap.min.js" %} ></script>
  </body>
</html>

src/templates/base2.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Органайзер</title>
</head>
<body>
    <header>
        
    </header>
</body>
</html>