src/notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path("", views.NotesView.as_view(), name='main'),
    path("create/", views.CreateNote.as_view(), name='create'),
    path("update/<int:pk>", views.UpdateNote.as_view(), name='update'),
    path("list", views.ListNote.as_view(), name='list'),
    path("delete/<int:pk>", views.DeleteNote.as_view(), name='delete'),
    path("detail/<int:pk>", views.DetailNote.as_view(), name='detail'),
]

src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='homepage/login_dj.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include('homepage.urls', namespace='homepage')),
    path("expences/", include('expences.urls'), name="expences"),
    path("notes/", include('notes.urls'), name="notes"),
    path("user/", include('user_register.urls'), name="user"),
    path("sport/", include('sport.urls'), name="sport")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/notes/models.py
from django.db import models
from django.contrib.auth import get_user_model

user_n = get_user_model()


class Notes(models.Model):
    user = models.ForeignKey(
        user_n,
        verbose_name='Пользователь',
        related_name='user_notes',
        on_delete=models.PROTECT
    )
    text = models.TextField(
        verbose_name='Заметка'
    )
    create_date = models.DateField(
        verbose_name='Дата создания',
        auto_now=False,
        auto_now_add=True
    )
    update_date = models.DateTimeField(
        verbose_name='Время изменения',
        auto_now=True
    )

src/notes/forms.py
from django import forms
from . import models


class NotesForm(forms.ModelForm):
    class Meta:
        model = models.Notes
        fields = ('text',)

src/notes/views.py
from django.shortcuts import render
from . import models, forms
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from expences.date_day_to import date


class NotesView(LoginRequiredMixin, generic.TemplateView):
    template_name = "notes/main.html"
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = models.Notes.objects.filter(
            Q(user=self.request.user) & Q(update_date__year=date.year, update_date__month=date.month))
        return context


class CreateNote(LoginRequiredMixin, generic.CreateView):
    model = models.Notes
    form_class = forms.NotesForm
    template_name = "notes/edit_note.html"
    success_url = reverse_lazy('notes:main')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Создать заметку'
        return context

    def form_valid(self, form):
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)


class UpdateNote(LoginRequiredMixin, generic.UpdateView):
    model = models.Notes
    template_name = "notes/edit_note.html"
    success_url = reverse_lazy('notes:main')
    login_url = reverse_lazy('login')
    form_class = forms.NotesForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Изменить заметку'
        return context


class ListNote(LoginRequiredMixin, generic.ListView):
    model = models.Notes
    template_name = "notes/list_note.html"
    login_url = reverse_lazy('login')

    def get_queryset(self):
        user = self.request.user
        object_list = models.Notes.objects.filter(user=user)
        return object_list


class DetailNote(LoginRequiredMixin, generic.DetailView):
    model = models.Notes
    template_name = "notes/detail_note.html"
    login_url = reverse_lazy('login')


class DeleteNote(LoginRequiredMixin, generic.DeleteView):
    model = models.Notes
    template_name = "notes/delete_note.html"
    success_url = reverse_lazy('notes:main')
    login_url = reverse_lazy('login')

src/notes/templates/notes/delete_note.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<ul>
<li>{{object.user}}</li>
<li>{{object.text}}</li>
<li>{{object.create_date}}</li>
<li>{{object.update_date}}</li>
</ul>
<h1>Удаляем данную  заметку?</h1>
    <form method = 'post'>
        {%csrf_token%}           
        <button type="submit" class="btn btn-danger">ДА</button>
    </form>


{% endblock body %}

src/notes/templates/notes/detail_note.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<ul>
    <li>Автор: <b>{{object.user}}</b></li>
    <li>Дата создания: <b>{{object.create_date}}</b></li>
    <li>Дата изменениния: <b>{{object.update_date}}</b></li>
    <li>Текст: <b>{{object.text}}</b></li>
<br><br>
<ul>
{% endblock body %}

src/notes/templates/notes/edit_note.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{operation}} {% endblock title %}

{% block body %}
<h1>{{operation}} </h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form |crispy}}
<input type="submit" class="btn btn-success" value="Ok">
</form>
{% endblock body %}

src/notes/templates/notes/list_note.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}



{% block body %}
<h1>Заметки</h1>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        <td>{{obj.user}}</td>
        <td>{{obj.create_date}}</td>
        <td>{{obj.update_date}}</td>
        <td><a href= "{% url 'notes:detail' pk=obj.pk %}" class="btn btn-secondary"><i class="bi bi-info-circle"></i></a></td>
        <td><a href= "{% url 'notes:update' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'notes:delete' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>
<li><a href="{% url 'notes:create' %}">Добавить заметку</a></li>
{% endblock body %}

src/notes/templates/notes/main.html
{% extends 'base.html' %}


{% block title %}Заметки{% endblock title %}

{% block body %}
<h1>Заметки</h1>
<ul>
    <li><a href="{% url 'notes:create'  %}">Создать заметку</a></li>
    <li><a href="{% url 'notes:list' %}">Список заметок</a></li>

</ul>
<br>
<br>
<br>
<br>
<br>
<br>
<div> 
<p>Заметки за текущий месяц:</p>
{% for obj in object_list %}
<ul><i class="bi bi-journal-check"></i>
    <li>изменена: {{obj.update_date}}</li>
    <li>заметка: {{obj.text}}</li>
</ul>
{% endfor %}
</div>
{% endblock body %}