src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(template_name='homepage/login_dj.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("", include('homepage.urls', namespace='homepage')),
    path("expences/", include('expences.urls'), name="expences"),
    path("notes/", include('notes.urls'), name="notes"),
    path("user/", include('user_register.urls'), name="user"),
    path("sport/", include('sport.urls'), name="sport")

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/sport/urls.py
from django.urls import path
from . import views

app_name = "sport"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="main"),

    path("subscription/", views.SubscriptionView.as_view(), name="subscription"),
    path("create-subscription", views.SubscriptionCreateView.as_view(), name="create-subscription"),
    path("list-subscription/", views.SubscriptionListView.as_view(), name="list-subscription"),
    path("update-subscription/<int:pk>", views.SubscriptionUpdateView.as_view(), name="update-subscription"),
    path("detail-subscription/<int:pk>", views.SubscriptionDetailView.as_view(), name="detail-subscription"),
    path("delete-subscription/<int:pk>", views.SubscriptionDeleteView.as_view(), name="delete-subscription"),


    path("create-subscription-visit", views.SubscriptionVisitCreateView.as_view(), name="create-subscription-visit"),
    path("list-subscription-visit/", views.SubscriptionVisitListView.as_view(), name="list-subscription-visit"),
    path("update-subscription-visit/<int:pk>", views.SubscriptionVisitUpdateView.as_view(), name="update-subscription-visit"),
    path("delete-subscription-visit/<int:pk>", views.SubscriptionVisitDeleteView.as_view(), name="delete-subscription-visit"),

]

src/sport/models.py
from django.db import models
from django.contrib.auth import get_user_model
from datetime import date

user = get_user_model()

class SubscriptionModel(models.Model):
    X = 'Безлимитный'
    Y = ' На количество занятий'

    CHOISE_GROUP = {
        (X, 'Расчет за полный месяц'),
        (Y, 'Расчет по мере зачисления на карту'),
    }

    user = models.ForeignKey(
        user,
        verbose_name='Пользователь',
        related_name='user_subscription',
        on_delete=models.PROTECT
    )
    name = models.CharField(
        verbose_name='Наименование',
        max_length=50)

    datestart = models.DateField(
        verbose_name='Дата начала абонемента', 
        auto_now_add=True)

    status = models.BooleanField(
        verbose_name='Активный'
    )

    quantity = models.SmallIntegerField(
        verbose_name='Количество занятий',

    )
    @property
    def datestop(self):
        dates = date(self.datestart.year, self.datestart.month+1, self.datestart.day)
        return dates
    
    @property
    def leftover(self):
        train = self.subscription_subscription_visits.all().count()
        left = self.quantity - train
        if left == 1:
            self.status = False
            self.save()
        return left


class SubscriptionVisit(models.Model):
    user = models.ForeignKey(
        user,
        verbose_name='Пользователь',
        related_name='user_subscription_visits',
        on_delete=models.PROTECT
    )
    subscription = models.ForeignKey(
        'sport.SubscriptionModel',
        verbose_name='Абонемент',
        related_name='subscription_subscription_visits',
        on_delete=models.CASCADE
    )
    visit_date = models.DateTimeField(
        verbose_name='Дата посещения',
        auto_now_add=True,

    )
    info = models.CharField(
        verbose_name='Комментарий',
        max_length=50,
        blank=True,
        null=True)
    

src/sport/forms.py
from django import forms
from . import models

class SubscriptionForm(forms.ModelForm):
    class Meta:
        model = models.SubscriptionModel
        fields = ('name', 'quantity','status')


class SubscriptionVisitsForm(forms.ModelForm):
    class Meta:
        model = models.SubscriptionVisit
        fields = ('info','subscription')

src/sport/views.py
from django.shortcuts import render, redirect
from . import models, forms
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from datetime import datetime


class HomepageView(LoginRequiredMixin,generic.TemplateView):
    login_url = reverse_lazy('login')
    template_name = "sport/sport_main.html"

class SubscriptionView(LoginRequiredMixin,generic.TemplateView):
    template_name = "sport/subscription.html"
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = models.SubscriptionModel.objects.filter(Q(user=self.request.user) & Q(status=True)).order_by('-datestart')
        return context



class SubscriptionCreateView(LoginRequiredMixin,generic.CreateView):
    model = models.SubscriptionModel
    form_class = forms.SubscriptionForm    
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('sport:subscription')
    template_name = "sport/edit_subscription.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Добавить абонемент'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SubscriptionUpdateView(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.SubscriptionModel
    form_class = forms.SubscriptionForm
    template_name = "sport/edit_subscription.html"
    success_url = reverse_lazy('sport:subscription')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Внести изменения'
        return context


    def test_func(self):
        for_test = self.get_object()
        if self.request.user == for_test.user:
            return True
        else:
            return False


class SubscriptionDeleteView(UserPassesTestMixin, LoginRequiredMixin, generic.DeleteView):
    model = models.SubscriptionModel
    template_name = "sport/delete_subscription.html"
    success_url = reverse_lazy('sport:subscription')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Удаление абонемента'
        context["alert_message"] = 'Вы точно хотите удалить данный абонемент???'
        return context

    def test_func(self):
        for_test = self.get_object()
        if self.request.user == for_test.user:
            return True
        else:
            return False

class SubscriptionDetailView(UserPassesTestMixin, LoginRequiredMixin, generic.DetailView):
    model = models.SubscriptionModel
    template_name = "sport/detail_subscription.html"
    login_url = reverse_lazy('login')

    def test_func(self):
        for_test = self.get_object()
        if self.request.user == for_test.user:
            return True
        else:
            return False


class SubscriptionListView(LoginRequiredMixin, generic.ListView):
    model = models.SubscriptionModel
    template_name = "sport/list_subscription.html"
    login_url = reverse_lazy('login')

    def get_queryset(self):
        object_list = models.SubscriptionModel.objects.filter(
            user=self.request.user)
        return object_list





# ##################################################################################



class SubscriptionVisitCreateView(LoginRequiredMixin,generic.CreateView):
    model = models.SubscriptionVisit
    form_class = forms.SubscriptionVisitsForm
    login_url = reverse_lazy('login')
    success_url = reverse_lazy('sport:subscription')
    template_name = "sport/add_train.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Создать'
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)




class SubscriptionVisitListView(LoginRequiredMixin, generic.ListView):
    model = models.SubscriptionVisit
    template_name = "sport/list_subscription_visit.html"
    login_url = reverse_lazy('login')

    def get_queryset(self):
        # subscription = models.SubscriptionVisit.objects.all()
        # print(subscription)
        # train = self.subscription_subscription_visits.all().count()
        train = models.SubscriptionVisit.subscription
        print(train)
        object_list = models.SubscriptionVisit.objects.filter(Q(user=self.request.user))
        return object_list

class SubscriptionVisitDeleteView(UserPassesTestMixin, LoginRequiredMixin, generic.DeleteView):
    model = models.SubscriptionVisit
    template_name = "sport/delete_subscription_visit.html"
    success_url = reverse_lazy('sport:subscription')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Удаление тренировки'
        context["alert_message"] = 'Вы точно хотите удалить данную запись о тренировке???'
        return context

    def test_func(self):
        for_test = self.get_object()
        if self.request.user == for_test.user:
            return True
        else:
            return False

class SubscriptionVisitUpdateView(UserPassesTestMixin, LoginRequiredMixin, generic.UpdateView):
    model = models.SubscriptionVisit
    form_class = forms.SubscriptionVisitsForm
    template_name = "sport/edit_subscription_visit.html"
    success_url = reverse_lazy('sport:subscription')
    login_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["operation"] = 'Внести изменения'
        return context


    def test_func(self):
        for_test = self.get_object()
        if self.request.user == for_test.user:
            return True
        else:
            return False

src/sport/templates/sport/add_train.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Добавить тренировку{% endblock title %}

    {% block body %}
    <a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
    <br>
    <h1>Добавить тренировку </h1>
    
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form |crispy}}
    <input type="submit" class="btn btn-success" value="Ok">
    </form>
    {% endblock body %}

src/sport/templates/sport/delete_subscription_visit.html
{% extends 'base.html' %}
{% block title %}Удалить абонемент{% endblock title %}

{% block body %}

<p>Удалить абонемент?</p>

    <p>{{object.name}} </p>
    <p>{{object.info}}</p>
    <p>{{object.}}</p>
    <p>{{object.quantity}}</p> 
<form method = 'post'>
    {%csrf_token%}           
    <button type="submit" class="btn btn-danger">ДА</button>
</form>

{% endblock body %}

src/sport/templates/sport/detail_subscription.html
{% extends 'base.html' %}
{% block title %}Подробнее{% endblock title %}

{% block body %}

<p>Подробнее</p>



{% endblock body %}

src/sport/templates/sport/edit_subscription.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{operation}} {% endblock title %}

{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<br>
<h1>{{operation}} </h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form |crispy}}
<input type="submit" class="btn btn-success" value="Ok">
</form>
{% endblock body %}

src/sport/templates/sport/edit_subscription_visit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} {{operation}} {% endblock title %}

{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<br>
<h1>{{operation}} </h1>

<div>
    <form action="{% url 'sport:update-subscription-visit' pk=object.pk %}" method="post">
        {% csrf_token %}
        <p><button type="submit" class="btn btn-success">Ok</button></p>
        <p>Комментарий:<input type="text" name="info" ></p>
        <input type="hidden" name="subscription" value="{{object.subscription.pk}}">    
    </form>
</div>
{% endblock body %}

src/sport/templates/sport/list_subscription.html
{% extends 'base.html' %}
{% block title %}Список абонементов{% endblock title %}

{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<h1>Список абонементов</h1>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        {% if obj.status == True %}
        <td>{{obj.name}} </td>
        <td>{{obj.datestart}}</td>
        <td>{{obj.status}}</td>
        <td>{{obj.quantity}}</td>
        <td><a class="subscription-main-block-link" href  ="{% url 'sport:list-subscription-visit' %}"><i class="bi bi-card-list"></i>&nbspСписок тренировок</a></p></td>
        <td> 
            {% if obj.status == True %}
            Активный
            {% else %}
            Окончен
            {% endif %}
        </td>
        {% else %}
        <td><s>{{obj.name}} </s></td>
         <td><s>{{obj.datestart}}</s></td>
        <td><s>{{obj.status}}</s></td>
        <td><s>{{obj.quantity}}</s></td>
            {% if obj.status == True %}
            Не оплачено
            {% else %}
            Оплачено
            {% endif %}
        </td>
        {% endif %}
        <td><a href= "{% url 'sport:detail-subscription' pk=obj.pk %}" class="btn btn-secondary"><i class="bi bi-info-circle"></i></a></td>
        <td><a href= "{% url 'sport:update-subscription' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'sport:delete-subscription' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>

<p><a href="{% url 'sport:create-subscription' %}">Добавить абонемент</a></p>
{% endblock body %}

src/sport/templates/sport/list_subscription_visit.html
{% extends 'base.html' %}
{% block title %}Список тренировок{% endblock title %}

{% block body %}
<a href="javascript:history.back()"><button type="button" class="btn btn-light"><i class="bi bi-arrow-left-square-fill"></i> назад</button></a>
<h1>Список тренировок</h1>
<table class="table table-dark table-striped">
    {% for obj in object_list %}
    <tr>
        <td>{{obj.subscription.name}} </td>
        <td>{{obj.visit_date}}</td>
        <td>{{obj.info}}</td>
        <td><a href= "{% url 'sport:update-subscription-visit' pk=obj.pk %}" class="btn btn-info"><i class="bi bi-pencil-fill"></i></a></td>
        <td><a href= "{% url 'sport:delete-subscription-visit' pk=obj.pk %}" class="btn btn-danger"><i class="bi bi-trash"></i></a></td>
    </tr>
    {% endfor %}
</table>
{% endblock body %}

src/sport/templates/sport/sport_main.html
{% extends 'base.html' %}
{% block title %}
Спорт
{% endblock title %}
{% block body %}
<div class="sport-main-block">
    <a class="sport-main-block-link" href ="{% url 'sport:subscription' %}">Абонементы</a>
</div>



{% endblock body %}

src/sport/templates/sport/subscription.html
{% extends 'base.html' %}
{% block title %}
Абонемент
{% endblock title %}
{% block body %}
<div class="sport-main-block">
    <h2>Абонеметы</h2>
        <p><a class="sport-main-block-link" href ="{% url 'sport:create-subscription' %}"><i class="bi bi-plus-circle"></i> Добавить</a></p>
        <p><a class="sport-main-block-link" href ="{% url 'sport:list-subscription' %}"><i class="bi bi-card-list"></i> Список абонемнеметов</a></p>
        <hr/>
</div>

{% for obj in object_list %}
<div class="subscription-card">
<p>Название: {{obj.name}}</p>    
<p>Дата начала: {{obj.datestart}}</p>
<p>Дата окончания: {{obj.datestop}}</p>
<p>Всего занятий: {{obj.quantity}}&nbsp|&nbspОсталось занятий: {{obj.leftover }}</p>
<hr/>
<div>
    <form action="{% url 'sport:create-subscription-visit' %}" method="post">
        {% csrf_token %}
        <p><button class="post-subscription-button" type="submit" class="btn btn-success">Добавить тренировку</button></p>
        <input type="hidden" name="subscription" value="{{obj.pk}}">    
        <details>
            <summary>Комментарий:</summary>
        <p><input class="field-input-subscription" type="text" name="info" placeholder="Тренировка ног..." ></p>
        </details>
    </form>
</div>
<hr/>
<p><a class="subscription-main-block-link" href  ="{% url 'sport:list-subscription-visit' %}"><i class="bi bi-card-list"></i>&nbspСписок тренировок</a></p>
</div>
{% endfor %}


{% endblock body %}